// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgFLiCHnwaYv2YSw1zf42LLtXjb99-QuM',
    appId: '1:653633350382:web:c0a7daf819119e632ee1ff',
    messagingSenderId: '653633350382',
    projectId: 'irnews-c84d2',
    authDomain: 'irnews-c84d2.firebaseapp.com',
    storageBucket: 'irnews-c84d2.firebasestorage.app',
    measurementId: 'G-7M8R2162HL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx7ltx3F1tlxfovBlhTkq_-i-674OlA28',
    appId: '1:653633350382:android:a3c114908746f3422ee1ff',
    messagingSenderId: '653633350382',
    projectId: 'irnews-c84d2',
    storageBucket: 'irnews-c84d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAG6H0lqzKlAoXXdyBi7bqyFZC4fbwPMw',
    appId: '1:653633350382:ios:3a764e715544054a2ee1ff',
    messagingSenderId: '653633350382',
    projectId: 'irnews-c84d2',
    storageBucket: 'irnews-c84d2.firebasestorage.app',
    iosBundleId: 'com.example.lrNews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAG6H0lqzKlAoXXdyBi7bqyFZC4fbwPMw',
    appId: '1:653633350382:ios:3a764e715544054a2ee1ff',
    messagingSenderId: '653633350382',
    projectId: 'irnews-c84d2',
    storageBucket: 'irnews-c84d2.firebasestorage.app',
    iosBundleId: 'com.example.lrNews',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgFLiCHnwaYv2YSw1zf42LLtXjb99-QuM',
    appId: '1:653633350382:web:ddb03bcd05b64ba62ee1ff',
    messagingSenderId: '653633350382',
    projectId: 'irnews-c84d2',
    authDomain: 'irnews-c84d2.firebaseapp.com',
    storageBucket: 'irnews-c84d2.firebasestorage.app',
    measurementId: 'G-7FC8VJ55HQ',
  );
}
