// lib/utils/updated_constants.dart
import 'package:flutter/material.dart';
import 'dart:io';

class AppColors {
  static const Color primaryColor = Color(0xFF2196F3);
  static const Color secondaryColor = Color(0xFF03DAC6);
  static const Color backgroundColor = Color(0xFFF5F5F5);
  static const Color errorColor = Color(0xFFB00020);
  static const Color successColor = Color(0xFF4CAF50);
  static const Color warningColor = Color(0xFFFF9800);
  static const Color cardColor = Colors.white;
  static const Color textPrimary = Color(0xFF212121);
  static const Color textSecondary = Color(0xFF757575);

  // 뉴스 카테고리 색상
  static const Map<String, Color> categoryColors = {
    '인기': Color(0xFFFF5722),
    '정치': Color(0xFF3F51B5),
    '경제': Color(0xFF4CAF50),
    '산업': Color(0xFF607D8B),
    '사회': Color(0xFF9C27B0),
    '문화': Color(0xFFE91E63),
    '과학': Color(0xFF00BCD4),
    '스포츠': Color(0xFFFF9800),
    '연예': Color(0xFFCDDC39),
  };
}

class ApiConstants {
  // 실제 기기용 기본 URL
  static String get baseUrl {
    return 'http://172.30.1.13:3000/api';
  }

  // 연결 시도할 URL 목록 (우선순위순)
  static List<String> get possibleUrls {
    return [
      'http://172.30.1.13:3000/api',    // 실제 PC IP
      'http://localhost:3000/api',
      'http://127.0.0.1:3000/api',
      'http://10.0.2.2:3000/api',        // 안드로이드 에뮬레이터용
    ];
  }

  // News API 키 - 실제 서비스에서는 환경변수나 secure storage 사용
  static const String newsApiKey = '4298913bb759467bbf9d04dbdddb9749';

  // 뉴스 API 엔드포인트
  static const String newsApiBaseUrl = 'https://newsapi.org/v2';

  // 한국 뉴스 소스들
  static const List<String> koreanNewsSources = [
    'yonhap-news-agency',
    // 추가적인 한국 뉴스 소스가 있다면 여기에 추가
  ];
}

class AppStrings {
  static const String appName = '뉴스 디베이터';
  static const String errorNetwork = '네트워크 연결을 확인해주세요';
  static const String errorGeneral = '오류가 발생했습니다';
  static const String loading = '로딩 중...';
  static const String noData = '데이터가 없습니다';
  static const String retry = '다시 시도';

  // 뉴스 관련
  static const String newsExplorer = '뉴스 탐색';
  static const String realTimeNews = '실시간 뉴스';
  static const String debateIssues = '논쟁 이슈';
  static const String autoGeneratedIssue = '자동 생성된 이슈';
  static const String createIssueFromNews = '이슈로 등록';

  // 카테고리 관련
  static const String allCategories = '전체';
  static const String popularNews = '인기 뉴스';
  static const String categoryNews = '카테고리별 뉴스';

  // 에러 메시지
  static const String failedToLoadNews = '뉴스를 불러올 수 없습니다';
  static const String failedToLoadIssues = '이슈를 불러올 수 없습니다';
  static const String serverConnectionError = '서버에 연결할 수 없습니다';
}

class AppDimensions {
  static const double padding = 16.0;
  static const double margin = 8.0;
  static const double borderRadius = 12.0;
  static const double cardElevation = 2.0;

  // 뉴스 카드 관련
  static const double newsImageHeight = 150.0;
  static const double categoryChipHeight = 40.0;
  static const double tagChipHeight = 32.0;
}

class AppDurations {
  static const Duration animationShort = Duration(milliseconds: 200);
  static const Duration animationMedium = Duration(milliseconds: 300);
  static const Duration animationLong = Duration(milliseconds: 500);

  // API 타임아웃
  static const Duration apiTimeout = Duration(seconds: 30);
  static const Duration newsRefreshInterval = Duration(minutes: 15);
}

// 뉴스 키워드 매핑 클래스
class NewsKeywords {
  // 카테고리별 키워드
  static const Map<String, List<String>> categoryKeywords = {
    '정치': [
      '국정감사', '국회', '대통령', '정부', '여당', '야당', '선거', '정책',
      '법안', '의원', '국정', '정치', '민주당', '국민의힘', '정당'
    ],
    '경제': [
      '경제', '금리', '환율', '주가', '증시', '코스피', '코스닥', 'GDP',
      '인플레이션', '물가', '투자', '금융', '은행', '기업', '매출'
    ],
    '산업': [
      '삼성', 'LG', '현대', '기업', '산업', '제조업', '반도체', '자동차',
      '조선', '건설', '화학', '철강', '에너지', '생산', '공장'
    ],
    '사회': [
      '사회', '교육', '의료', '복지', '범죄', '사고', '재해', '안전',
      '환경', '교통', '주택', '인구', '고령화', '청년', '일자리'
    ],
    '문화': [
      '문화', '예술', '영화', '드라마', '음악', '전시', '공연', '축제',
      '관광', '여행', '한류', 'K-POP', '문화재', '박물관', '갤러리'
    ],
    '과학': [
      '과학', '기술', 'IT', 'AI', '인공지능', '연구', '개발', '혁신',
      '디지털', '바이오', '우주', '로봇', '빅데이터', '클라우드', '5G'
    ],
    '스포츠': [
      '스포츠', '축구', '야구', '농구', '배구', '골프', '테니스', '올림픽',
      '월드컵', '선수', 'KBO', 'K리그', '프로스포츠', '경기', '결승'
    ],
    '연예': [
      '연예', '아이돌', '가수', '배우', '방송', 'K-POP', '드라마', '예능',
      '엔터테인먼트', '셀럽', '콘서트', '앨범', '영화제', '시상식', '데뷔'
    ],
  };

  // 태그별 세부 키워드
  static const Map<String, Map<String, List<String>>> tagKeywords = {
    '정치': {
      '국내': ['국내정치', '한국정치', '내정', '국정', '청와대', '국무총리'],
      '글로벌': ['국제정치', '외교', '국제관계', '해외', '외무부', '대사관'],
      '미국': ['미국', '바이든', '트럼프', '백악관', '워싱턴', '국무부'],
      '북한': ['북한', '김정은', '평양', '핵', '미사일', '통일부'],
      '일본': ['일본', '기시다', '도쿄', '독도', '위안부', '과거사'],
      '중국': ['중국', '시진핑', '베이징', '사드', '무역전쟁', '외교부'],
    },
    '경제': {
      '주식': ['주식', '증권', '투자', '상장', '배당', '주주', '코스피', '코스닥'],
      '코인': ['비트코인', '암호화폐', '가상화폐', '블록체인', '이더리움', '코인'],
      '부동산': ['부동산', '아파트', '집값', '전세', '매매', '임대', '분양'],
      '금융': ['은행', '금융', '대출', '예금', '보험', '카드', '핀테크'],
      '무역': ['수출', '수입', '무역', '관세', '무역수지', 'FTA', '통상'],
    },
    '산업': {
      '반도체': ['반도체', '칩', '메모리', '삼성전자', 'SK하이닉스', '파운드리'],
      '자동차': ['자동차', '현대차', '기아', '전기차', 'EV', '배터리'],
      '조선': ['조선', '선박', '현대중공업', '대우조선해양', '삼성중공업'],
      '철강': ['철강', '포스코', '제철', '스테인리스', '철광석'],
      '화학': ['화학', '석유화학', 'LG화학', 'SK케미칼', '정유'],
    },
    '사회': {
      '교육': ['교육', '학교', '대학', '입시', '수능', '사교육', '교사'],
      '의료': ['의료', '병원', '코로나', '백신', '질병', '의사', '간호사'],
      '환경': ['환경', '기후변화', '탄소중립', '미세먼지', '재활용'],
      '안전': ['안전', '사고', '재해', '화재', '교통사고', '안전사고'],
    },
    '문화': {
      'K-컬처': ['한류', 'K-POP', 'K-드라마', '한국문화', '케이컬처'],
      '영화': ['영화', '시네마', '영화제', '박스오피스', '감독', '배우'],
      '드라마': ['드라마', 'TV', '방송', 'OTT', '넷플릭스', '시청률'],
      '관광': ['관광', '여행', '축제', '문화재', '유네스코', '명소'],
    },
    '과학': {
      'IT': ['IT', '정보기술', '소프트웨어', '앱', '플랫폼', '디지털'],
      'AI': ['AI', '인공지능', '머신러닝', '딥러닝', '로봇', '자동화'],
      '바이오': ['바이오', '생명과학', '의학', '신약', '백신', '유전자'],
      '우주': ['우주', '항공', '위성', '로켓', 'NASA', '달탐사'],
    },
    '스포츠': {
      '축구': ['축구', '월드컵', '손흥민', '국가대표', 'K리그', 'FIFA'],
      '야구': ['야구', 'KBO', '프로야구', '월드베이스볼클래식', 'WBC'],
      '올림픽': ['올림픽', '패럴림픽', '아시안게임', 'IOC', '금메달'],
      'e스포츠': ['e스포츠', '게임', 'LoL', '프로게이머', '리그오브레전드'],
    },
    '연예': {
      'K-POP': ['K-POP', '아이돌', 'BTS', '블랙핑크', '케이팝', '한류'],
      '드라마': ['드라마', 'K-드라마', '넷플릭스', '방송', '배우'],
      '예능': ['예능', '버라이어티', '토크쇼', 'MBC', 'KBS', 'SBS'],
      '영화': ['영화배우', '한국영화', '칸영화제', '아카데미', '시상식'],
    },
  };

  // 논쟁적 키워드 (이슈 생성용)
  static const List<String> controversialKeywords = [
    '논란', '반대', '찬성', '갈등', '대립', '비판', '우려', '환영',
    '반발', '항의', '토론', '논쟁', '의견', '입장', '견해', '쟁점',
    '찬반', '대립각', '갈등', '분열', '격론', '공방'
  ];

  // 긍정적 키워드 (찬성 측면)
  static const List<String> positiveKeywords = [
    '환영', '찬성', '긍정', '지지', '호응', '추진', '개선', '발전',
    '혁신', '진보', '효과', '성과', '기대', '희망', '성공'
  ];

  // 부정적 키워드 (반대 측면)
  static const List<String> negativeKeywords = [
    '반대', '우려', '비판', '논란', '반발', '문제', '위험', '부작용',
    '걱정', '염려', '한계', '단점', '실패', '위기', '충격'
  ];
}